In [1]:
import glob
import pandas as pd

arquivos = glob.glob(r"dados-originais/*.csv")
print(arquivos)
df = pd.read_csv(arquivos[0], sep=";")

['dados-originais\\Pre�os semestrais - AUTOMOTIVOS_2026.01.csv']

In [2]:
df.shape

(422418, 16)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422418 entries, 0 to 422417
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     422418 non-null  object
 1   Estado - Sigla     422418 non-null  object
 2   Municipio          422418 non-null  object
 3   Revenda            422418 non-null  object
 4   CNPJ da Revenda    422418 non-null  object
 5   Nome da Rua        422418 non-null  object
 6   Numero Rua         422412 non-null  object
 7   Complemento        96159 non-null   object
 8   Bairro             421690 non-null  object
 9   Cep                422418 non-null  object
 10  Produto            422418 non-null  object
 11  Data da Coleta     422418 non-null  object
 12  Valor de Venda     422418 non-null  object
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  422418 non-null  object
 15  Bandeira           422418 non-null  object
dtypes: float64(1), object(15)
memory usage: 51.6+ MB

In [4]:
df.isna().sum()

Regiao - Sigla            0
Estado - Sigla            0
Municipio                 0
Revenda                   0
CNPJ da Revenda           0
Nome da Rua               0
Numero Rua                6
Complemento          326259
Bairro                  728
Cep                       0
Produto                   0
Data da Coleta            0
Valor de Venda            0
Valor de Compra      422418
Unidade de Medida         0
Bandeira                  0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(6)

In [6]:
df.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,GASOLINA,02/01/2026,"7,97",NaN,R$ / litro,IPIRANGA
1,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL,02/01/2026,"8,15",NaN,R$ / litro,IPIRANGA
2,N,AC,CRUZEIRO DO SUL,AMAZONIA COMERCIO DE DERIVADOS DE PETROLEO LTDA,01.492.748/0003-83,AVENIDA COPACABANA,440,NaN,COPACABANA,69980-000,DIESEL S10,02/01/2026,"8,17",NaN,R$ / litro,IPIRANGA
3,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA,02/01/2026,"7,29",NaN,R$ / litro,VIBRA
4,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA ADITIVADA,02/01/2026,"7,39",NaN,R$ / litro,VIBRA

In [7]:
df.columns

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='object')

In [8]:
df_rs = df[df["Estado - Sigla"] == "RS"].copy()
df_rs.shape

(31015, 16)

In [9]:
df_rs.columns = (df_rs.columns.str.strip().str.lower()
                 .str.replace(" - ", "_").str.replace(" ", "_"))

In [10]:
df_rs["valor_de_venda"] = pd.to_numeric(df_rs["valor_de_venda"].str.replace(",", "."), errors="coerce")
#Transformação de string para tipo numérico

In [11]:
df_rs = df_rs.drop(columns=["valor_de_compra"])

In [12]:
df_rs["data_da_coleta"].head()

249    02/01/2026
250    02/01/2026
251    02/01/2026
252    02/01/2026
253    02/01/2026
Name: data_da_coleta, dtype: object

In [13]:
df_rs["data_da_coleta"] = pd.to_datetime(df_rs["data_da_coleta"], dayfirst=True, errors="coerce")

In [14]:
df_rs.isna().sum()

regiao_sigla             0
estado_sigla             0
municipio                0
revenda                  0
cnpj_da_revenda          0
nome_da_rua              0
numero_rua               0
complemento          25580
bairro                 149
cep                      0
produto                  0
data_da_coleta           0
valor_de_venda           0
unidade_de_medida        0
bandeira                 0
dtype: int64

In [15]:
antes = df_rs["nome_da_rua"].nunique()
depois = df_rs["nome_da_rua"].str.strip().str.upper().nunique()
print(antes, depois)

343 343

In [16]:
df_rs["municipio"].value_counts()

municipio
PORTO ALEGRE             3069
PELOTAS                  1687
CAXIAS DO SUL            1679
SANTA MARIA              1315
NOVO HAMBURGO            1230
CANOAS                   1192
SANTA CRUZ DO SUL        1166
ERECHIM                  1064
BENTO GONCALVES           992
SAO LEOPOLDO              983
GUAIBA                    956
LAJEADO                   940
IJUI                      917
BAGE                      907
SANTO ANGELO              878
VACARIA                   859
SANTANA DO LIVRAMENTO     830
URUGUAIANA                728
VIAMAO                    718
CACHOEIRA DO SUL          717
SAPIRANGA                 713
SANTA ROSA                688
ESTEIO                    682
SAPUCAIA DO SUL           628
ALEGRETE                  615
SAO LUIZ GONZAGA          609
ALVORADA                  565
SAO GABRIEL               539
OSORIO                    531
GRAVATAI                  493
CRUZ ALTA                 490
TORRES                    462
CACHOEIRINHA              434
PASSO FUNDO               387
GRAMADO                   352
Name: count, dtype: int64

In [17]:
df_rs.duplicated().sum()

np.int64(6)

In [18]:
df_rs[df_rs.duplicated(keep=False)]

,regiao_sigla,estado_sigla,municipio,revenda,cnpj_da_revenda,nome_da_rua,numero_rua,complemento,bairro,cep,produto,data_da_coleta,valor_de_venda,unidade_de_medida,bandeira
101456,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,GASOLINA,2026-02-16,6.99,R$ / litro,IPIRANGA
101457,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,DIESEL S10,2026-02-16,5.99,R$ / litro,IPIRANGA
101458,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,ETANOL,2026-02-16,5.19,R$ / litro,IPIRANGA
101459,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,GASOLINA,2026-02-16,6.99,R$ / litro,IPIRANGA
101460,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,DIESEL S10,2026-02-16,5.99,R$ / litro,IPIRANGA
101461,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,ETANOL,2026-02-16,5.19,R$ / litro,IPIRANGA
101462,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,GASOLINA,2026-02-18,6.99,R$ / litro,IPIRANGA
101463,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,DIESEL S10,2026-02-18,5.99,R$ / litro,IPIRANGA
101464,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,ETANOL,2026-02-18,5.19,R$ / litro,IPIRANGA
101465,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,GASOLINA,2026-02-18,6.99,R$ / litro,IPIRANGA
101466,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,DIESEL S10,2026-02-18,5.99,R$ / litro,IPIRANGA
101467,S,RS,SANTA MARIA,H. D. PORTELLA & CIA LTDA,07.663.077/0001-90,AVENIDA FERNANDO FERRARI,1255,NaN,NOSSA SRA DE LOURDES,97050-801,ETANOL,2026-02-18,5.19,R$ / litro,IPIRANGA

In [19]:
antes = len(df_rs)
df_rs = df_rs.drop_duplicates()
print(antes, len(df_rs))

31015 31009

In [20]:
df_rs.duplicated(subset=["cnpj_da_revenda", "produto", "data_da_coleta"]).sum()

np.int64(0)

In [21]:
df_rs["data_da_coleta"].dtype

dtype('<M8[ns]')

In [22]:
df_rs["data_da_coleta"].isna().sum()

np.int64(0)

In [23]:
df_rs["data_da_coleta"].min(), df_rs["data_da_coleta"].max()

(Timestamp('2026-01-02 00:00:00'), Timestamp('2026-06-30 00:00:00'))

In [24]:
df_rs['valor_de_venda'].info()
df_rs['valor_de_venda'].describe()

<class 'pandas.core.series.Series'>
Index: 31009 entries, 249 to 422385
Series name: valor_de_venda
Non-Null Count  Dtype
--------------  -----
31009 non-null  float64
dtypes: float64(1)
memory usage: 484.5 KB

count    31009.000000
mean         6.396593
std          0.691411
min          4.090000
25%          6.170000
50%          6.490000
75%          6.790000
max          8.990000
Name: valor_de_venda, dtype: float64

In [25]:
df_rs["produto"].value_counts()

produto
GASOLINA              8332
GASOLINA ADITIVADA    7920
DIESEL S10            5646
DIESEL                4754
ETANOL                3861
GNV                    496
Name: count, dtype: int64

In [26]:
df_rs["bandeira"].value_counts()

bandeira
IPIRANGA            8983
BRANCA              8207
VIBRA               5952
RAIZEN              4165
CHARRUA             1926
RODOIL              1157
SANTA LUCIA          306
POTENCIAL            148
ALE                  105
SIM DISTRIBUIDOR      48
MAXSUL                12
Name: count, dtype: int64

In [27]:
df_rs["unidade_de_medida"].value_counts()

unidade_de_medida
R$ / litro    30513
R$ / m³         496
Name: count, dtype: int64

In [28]:
df_rs.groupby("produto")["valor_de_venda"].describe()

                     count      mean       std   min   25%   50%   75%   max
produto
DIESEL              4754.0  6.662463  0.568828  5.09  6.19  6.69  7.09  8.84
DIESEL S10          5646.0  6.782586  0.578941  5.35  6.32  6.79  7.19  8.99
ETANOL              3861.0  5.085056  0.397603  4.09  4.86  4.99  5.29  6.99
GASOLINA            8332.0  6.446152  0.280469  5.58  6.28  6.44  6.59  7.74
GASOLINA ADITIVADA  7920.0  6.639641  0.307797  5.58  6.44  6.62  6.81  7.99
GNV                  496.0  4.950464  0.259529  4.49  4.79  4.99  4.99  5.99

In [29]:
df_gnv = df_rs[df_rs["produto"] == "GNV"].copy()
df_rs = df_rs[df_rs["produto"] != "GNV"].copy()

In [30]:
df_gnv["valor_de_venda"].describe()

count    496.000000
mean       4.950464
std        0.259529
min        4.490000
25%        4.790000
50%        4.990000
75%        4.990000
max        5.990000
Name: valor_de_venda, dtype: float64

In [31]:
import os

pasta = r"C:\Users\admin\Desktop\limpeza-dados-combustivel\dados-limpos"
os.makedirs(pasta, exist_ok=True)

df_rs.to_csv(os.path.join(pasta, "combustiveis_liquidos_rs_2026_01.csv"), index=False, encoding="utf-8-sig")
df_rs.to_excel(os.path.join(pasta, "combustiveis_liquidos_rs_2026_01.xlsx"), index=False)
df_gnv.to_csv(os.path.join(pasta, "gnv_rs_2026_01.csv"), index=False, encoding="utf-8-sig")

In [32]:
df_rs.shape

(30513, 15)

In [33]:
df_gnv.shape

(496, 15)